name: Unit tests

on: [push]

jobs:
  build:
    env:
      CKANVERSION: '2.9.1'
      POSTGRES_HOST: 'localhost'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      PGHOST: 'localhost'
      PGPORT: '5432'

    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: postgres        
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5      
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '2.7'
          architecture: 'x64'
#      - name: Start Postgres
#        uses: harmon758/postgresql-action@v1
#        with:
#          postgresql version: '11' 
      - name: Start Redis
        uses: supercharge/redis-github-action@1.1.0
        with:
          redis-version: '6'
      - name: Install dependencies
        run: PGHOST=$PGHOST PGUSER=$POSTGRES_USER PGPASSWORD=$POSTGRES_PASSWORD bin/gh-build.bash
        shell: bash
      - name: Run tests
        run: PGHOST=$PGHOST PGUSER=$POSTGRES_USER PGPASSWORD=$POSTGRES_PASSWORD bin/gh-run.bash
        shell: bash
